import { runVisualApp } from "../helper/visualHelp.js";
import "./voxelHatchingShadows_visual.js";

document.addEventListener("DOMContentLoaded", () => {
  runVisualApp({
    visualId: "voxelHatchingShadows",
    mountEl: document.getElementById("vis"),
    uiEl: document.getElementById("config"),
    state: {
      seed: 41680039,
      gridSize: 152,
      voxelSize: 100,
      voxelGapRatio: 0.36,
      materialMode: "lambert",
      placementMode: "allow",
      shapeSpacing: 2,
      autoProceduralShapes: false,
      proceduralShapeCount: 12,
      proceduralScale: 1,
      proceduralSpread: 1,
      proceduralBaseRatio: 0.05,
      proceduralYawSteps: 2,
      erosionSteps: 6,
      erosionNeighbors: 4,
      dilationSteps: 5,
      dilationNeighbors: 6,
      surfaceNoise: 1,
      mirrorX: false,
      mirrorZ: false,
      rotateQuarterTurns: 0,
      randomSliceCount: 0,
      randomSliceThickness: 5,
      sliceRotX: 35,
      sliceRotY: 35,
      sliceRotZ: 35,
      showSliceVolumes: false,
      cameraDistance: 820,
      cameraAzimuth: 38,
      cameraElevation: 32,
      groundEnabled: true,
      groundScale: 20,
      groundYOffset: 20,
      groundOpacity: 1,
      groundColor: "#e2e5f0",
      backgroundColor: "#f7f8fb",
      lightAzimuth: 169,
      lightElevation: 25,
      lightDistance: 2000,
      lightIntensity: 4,
      ambientIntensity: 0,
      shadowExtent: 1200,
      shadowNear: 1,
      shadowFar: 20000,
      shadowMapSize: 2048,
      shadowBias: -0.0002,
      shadowNormalBias: 0,
      svgStrokeWidth: 1,
      svgFillOpacity: 1,
      svgStroke: "#ff0000",
      svgLineMode: "solid",
      svgCullInvisible: false,
      svgCullMinSize: 0,
      svgShadowEnabled: true,
      svgShadowStrokeWidth: 2.2,
      svgShadowStroke: "#ffffff",
      svgShadowHatchSpacingRatio: 0.66,
      svgShadowHatchAngle: -26,
      svgMergePaths: true,
      showSvgOverlay: true,
      shouldRender: true,
      __xf: {
        ui: {
          splitCount: 1,
          activeTile: "0",
          rotateDeg: 90,
          preset: "",
          splitMode: "screen",
          applyToAll: false,
          tileTargets: "0",
          zoomFactor: 1.25,
          matrix: {
            a: 1,
            b: 0,
            c: 0,
            d: 1,
            e: 0,
            f: 0,
          },
          zoomCenter: {
            x: null,
            y: null,
          },
          translateVec: {
            x: 0,
            y: 0,
          },
          planeCount: 3,
          planeBaseScale: 1,
          planeScaleStep: -0.12,
          planeOpacity: 0.7,
          planeOpacityFalloff: 0.12,
          planeOffset: {
            x: 0,
            y: 0,
          },
          planeCenter: {
            x: null,
            y: null,
          },
          groupOpen: {},
        },
        stack: [],
      },
      shapeTool: {
        mode: "translate",
        shape: "sphere",
        cursor: {
          x: -68,
          y: -32,
          z: 61,
        },
        rotation: {
          x: 0,
          y: -82,
          z: 0,
        },
        scale: 0.3,
        stretch: {
          x: 3,
          y: 3,
          z: 0.62,
        },
        colorIndex: 0,
      },
      shapeInstances: [
        {
          shape: "boxTall",
          position: { x: 0, y: -59, z: 11 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.67,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "boxTall",
          position: { x: 0, y: -59, z: -19 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.67,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "boxTall",
          position: { x: 0, y: -59, z: -45 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.67,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: 0, y: -21, z: -45 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.67,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: 0, y: -21, z: 14 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.67,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: -76, y: -21, z: 22 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.39,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: -76, y: -76, z: 22 },
          rotation: { x: 0, y: 55, z: 0 },
          scale: 0.39,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "boxTall",
          position: { x: 4, y: -53, z: 43 },
          rotation: { x: 0, y: -19, z: 0 },
          scale: 0.62,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "boxTall",
          position: { x: 4, y: -53, z: 76 },
          rotation: { x: 0, y: -19, z: 0 },
          scale: 0.62,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: 5, y: -19, z: 53 },
          rotation: { x: 0, y: -82, z: 0 },
          scale: 0.3,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: 5, y: -19, z: 76 },
          rotation: { x: 0, y: -82, z: 0 },
          scale: 0.3,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: -68, y: -19, z: 73 },
          rotation: { x: 0, y: -82, z: 0 },
          scale: 0.3,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: -68, y: -19, z: -5 },
          rotation: { x: 0, y: -82, z: 0 },
          scale: 0.3,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
        {
          shape: "sphere",
          position: { x: -68, y: -69, z: 61 },
          rotation: { x: 0, y: -82, z: 0 },
          scale: 0.3,
          stretch: { x: 3, y: 3, z: 0.62 },
          colorIndex: 0,
        },
      ],
      shapePanelCollapsed: true,
      __ui: {
        tabsOpen: false,
        activeTab: "params",
        paramGroups: {
          Primitives: false,
          Scene: false,
          Transforms: false,
          Camera: false,
          Light: true,
          SVG: true,
        },
        collapseParamsByDefault: true,
        ioOpen: true,
        configPinned: true,
        navHidden: false,
        configWidth: 542.359375,
      },
      __cameraPoseMeta: {
        distance: 820,
        azimuth: 38,
        elevation: 32,
      },
      __cameraPose: {
        position: [-20364.85723618571, -515.6735303859587, 3733.187953920993],
        target: [1224.147224243813, -6939.982857896864, 2082.198160110727],
      },
      __shapeCursorSeededToGround: false,
      __propOps: {
        ui: {
          ruleText: "{\n        \"selector\": {\"circle\":{\"r\":{\"range\":[20,100]}}},\n        \"apply\": {\"stroke\": null}\n        }",
          lastPreview: "",
          showDocs: false,
        },
        stack: [],
      },
      __scriptOps: {
        ui: {
          codeText: "// ctx.root is the <g> subtree being processed\n// ctx.svg is the owning <svg>\n// ctx.create(tag) creates an SVG element\n//\n// Example: circle -> 6-gon (polygon)\n// for (const c of ctx.root.querySelectorAll(\"circle\")) {\n//   const cx = Number(c.getAttribute(\"cx\") || 0);\n//   const cy = Number(c.getAttribute(\"cy\") || 0);\n//   const r = Number(c.getAttribute(\"r\") || 0);\n//   const n = 6;\n//   const pts = Array.from({length:n}, (_,i) => {\n//     const a = (Math.PI*2*i)/n;\n//     return [cx + r*Math.cos(a), cy + r*Math.sin(a)].join(\",\");\n//   }).join(\" \");\n//   const p = ctx.create(\"polygon\");\n//   p.setAttribute(\"points\", pts);\n//   for (const {name,value} of Array.from(c.attributes)) {\n//     if (name === \"cx\" || name === \"cy\" || name === \"r\") continue;\n//     p.setAttribute(name, value);\n//   }\n//   c.replaceWith(p);\n// }",
          fileName: "",
          selectedCacheKey: "",
          autoRunSelected: false,
          lastPreview: "",
          showDocs: false,
        },
        stack: [],
        cache: {},
      },
      __anim: {
        ui: {
          targetType: "params",
          paramTargets: [],
          paramKey: "",
          selector: "svg",
          svgKind: "attr",
          svgName: "opacity",
          durationSec: 3,
          fps: 20,
          easing: "linear",
          loop: false,
          yoyo: false,
          progress01: 0,
          autoFromCurrent: true,
          snapToEndOnStop: true,
          autoPlay: false,
        },
      },
    },
  });
});

function goTo(page) {
  window.location.href = page;
}
window.goTo = goTo;
